services:
  # PostgreSQL Database - ACID compliant for banking
  postgres:
    image: cgr.dev/chainguard/postgres:latest
    container_name: bank-postgres-test
    restart: unless-stopped
    environment:
      POSTGRES_DB: bankdb
      POSTGRES_USER: bankuser
      POSTGRES_PASSWORD: BankSecurePass2024!
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d:ro
    networks:
      - bank-network
    ports:
      - "5432:5432"

  # Backend API Service
  backend:
    image: chingnokas/cg-backbank:latest
    container_name: bank-backend-test
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://bankuser:BankSecurePass2024!@postgres:5432/bankdb
      SECRET_KEY: a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6
      ALLOWED_ORIGINS: http://frontend,http://localhost:3000
      APP_NAME: "Peoples Bank API"
      APP_VERSION: "1.0.0"
      DEBUG: "true"
    depends_on:
      - postgres
    networks:
      - bank-network
    ports:
      - "8000:8000"

  # Frontend Service
  frontend:
    image: chingnokas/cg-bank:latest
    container_name: bank-frontend-test
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - bank-network
    ports:
      - "3000:8080"

# Networks
networks:
  bank-network:
    driver: bridge

# Volumes for data persistence
volumes:
  postgres_test_data:
    driver: local
