name: Cleanup Cluster

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "yes" to confirm cleanup'
        required: true
        default: 'no'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'yes'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup DigitalOcean CLI
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - name: Setup Kubectl
        run: |
          echo "🔧 Setting up kubectl..."
          doctl kubernetes cluster kubeconfig save banking-app-k8s || echo "Cluster not found"

      - name: Cleanup Applications
        continue-on-error: true
        run: |
          echo "🧹 Cleaning up applications..."
          
          # Delete all deployments
          kubectl delete deployment --all -n banking-app --ignore-not-found=true
          kubectl delete statefulset --all -n banking-app --ignore-not-found=true
          
          # Delete all services
          kubectl delete service --all -n banking-app --ignore-not-found=true
          
          # Delete all ConfigMaps and Secrets
          kubectl delete configmap --all -n banking-app --ignore-not-found=true
          kubectl delete secret --all -n banking-app --ignore-not-found=true
          
          # Delete PVCs
          kubectl delete pvc --all -n banking-app --ignore-not-found=true
          
          # Delete monitoring namespace
          kubectl delete namespace monitoring --ignore-not-found=true
          
          # Delete banking-app namespace
          kubectl delete namespace banking-app --ignore-not-found=true
          
          echo "✅ Applications cleaned up"

      - name: Cleanup Cluster
        continue-on-error: true
        run: |
          echo "🗑️ Deleting Kubernetes cluster..."
          doctl kubernetes cluster delete banking-app-k8s --force || echo "Cluster already deleted"
          echo "✅ Cluster cleanup complete"

      - name: Summary
        run: |
          echo ""
          echo "🎯 CLEANUP COMPLETE!"
          echo "==================="
          echo ""
          echo "✅ All applications removed"
          echo "✅ All persistent volumes deleted"
          echo "✅ Kubernetes cluster deleted"
          echo ""
          echo "You can now run a fresh deployment!"
