name: Test Run - Banking App

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [main]  # Also trigger on push to main
  pull_request:
    branches: [main]

jobs:
  test-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test DigitalOcean Token
        run: |
          echo "🔍 Testing DigitalOcean setup..."
          
          if [ -z "${{ secrets.DIGITALOCEAN_TOKEN }}" ]; then
            echo "❌ DIGITALOCEAN_TOKEN secret is missing"
            echo "Add it at: https://github.com/${{ github.repository }}/settings/secrets/actions"
            exit 1
          fi
          
          echo "✅ DigitalOcean token is configured"
          echo "Token length: ${#DIGITALOCEAN_TOKEN}"
          echo "Token starts with: ${DIGITALOCEAN_TOKEN:0:8}..."
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - name: Configure DigitalOcean CLI
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - name: Test DigitalOcean API
        run: |
          echo "🌊 Testing DigitalOcean API access..."
          
          echo "Account info:"
          doctl account get
          
          echo ""
          echo "Existing clusters:"
          doctl kubernetes cluster list || echo "No clusters found"
          
          echo ""
          echo "✅ DigitalOcean API is working!"

      - name: Next Steps
        run: |
          echo "🎯 Test completed successfully!"
          echo ""
          echo "Next steps:"
          echo "1. This confirms your DigitalOcean token works"
          echo "2. Now we can run the full deployment"
          echo "3. Look for 'Sequential Banking App Deployment' workflow"
          echo ""
          echo "🚀 Ready to deploy your banking application!"
